### ISSUE TITLE
Macros?

### ISSUE THREAD

**Issue by mcarvette** [toddaustin07/edge_roku#1]
I'd love the ability to run some sort of macro (a sequence of remote button presses) that way a routine can be run from Smartthings to open a specific Roku channel and start playing. For example: open the CNN channel and start playing the live stream.

**Comment by toddaustin07** [comment]
Why couldn't you accomplish the same thing in the SmartThings automation routine (or Rule) itself?

In the old SmartThings world, this type of thing might be provided via a SmartApp.   It _might_ be able to be done via the Edge driver, but would be fairly awkward and kludgey.  The best place for this type of thing is in automation routines.
